### ISSUE TITLE
Layout is broken on most devices

### ISSUE THREAD

**Issue by RPrudden** [met-office-lab/wtforecast#2]
e.g. iPhone 4s
<img width="321" alt="screen shot 2016-05-09 at 16 24 37" src="https://cloud.githubusercontent.com/assets/9357195/15118074/8be88132-1602-11e6-87fc-7e115683ab10.png">

We need to make the layout responsive.

**Comment by jacobtomlinson** [comment]
Android is going to be a bigger pain as it's hard to predict all the possible sizes. 

That being said only Apple will reject broken UI layouts, Google won't.

**Comment by RPrudden** [comment]
Mainly fixed by https://github.com/met-office-lab/wtforecast/commit/ffac5b4f2726bf2a73efa935b1f806def393ca6c - will raise any specific issues separately.
